# Using python for running the tests, using the `cram` test framework.
language: python

python: "2.7"

install:
  - pip install cram
  - sudo apt-get zsh

script:
  - make test

notifications:
  email: false

branches:
  only:
    - master
