#!/bin/bash
#
# aurget config file
#
###

#
# the exact command used to install packages. --asdeps will be
# automatically added when appropriate. use --popt to add any additional
# options at runtime.
###
pacman_command='sudo pacman -U'

#
# the exact command used to build packages. --noconfirm is required
# since makepkg is run inside a subshell and you're unable to answer
# prompts. --syncdeps will be added if you choose to resolve
# dependencies. use --mopt to add any additional options at runtime.
###
makepkg_command='makepkg --noconfirm'

#
# by default, the value of $EDITOR is used to edit pkgbuilds.
# you can override this here if you'd like.
###
pkgbuild_editor=

#
# where to save built packages. if empty, the value of PKGDEST in
# makepkg.conf or the current working directory will be used.
###
package_directory=

#
# where to download source files and do the actual building. aurget
# will create subdirectories named after the packages being built.
# if empty, the current working directory will be used.
###
build_directory=

#
# if 0 (true), aurget will discard source files after building a package.
###
discard_sources=0

#
# if 0 (true), aurget will not discard sources of development packages as
# defined by development_regex regardless of the above setting.
###
dont_discard_devels=0

#
# this regex is matched against package names to determine if a package
# is a development package. development packages are not checked for
# available upgrades but can be included by passing --devel.
###
development_regex='.*-git$\|.*-hg$\|.*-svn$\|.*-darcs$\|.*-cvs$\|.*-bzr$'

#
# set this to 0 (true) and aurget will remove all makedepends that were
# installed as part of the operation as the last step in said operation.
# this option will be deprecated soon as makepkg can now handle this
# itself.
###
remove_makedepends=1

#
# the default sync mode is the one used when -S or -Su is called without
# explicitly passing y, b, or d. it can be one of install, build, or
# download.
###
sync_mode='install'

#
# this determines how the editing of pkgbuilds is handled. it can be
# one of always, never, or prompt.
###
edit_pkgbuilds='prompt'

#
# if 1 (true), aurget will automatically resolve dependencies.
###
resolve_dependencies=1

#
# a space separated list of package names to be ignored. please quote
# the entire list
###
ignore_packages=

#
# by default, aurget uses no color. uncomment to enable/customize.
###
#nocolor="\e[0m"   # reset color
#colorW="\e[1;37m" # white
#colorC="\e[1;36m" # cyan
#colorB="\e[1;34m" # blue
#colorR="\e[1;31m" # red
#colorG="\e[1;32m" # green
#colorY="\e[1;33m" # yellow
#colorM="\e[1;35m" # magenta
