#!/bin/bash
#
# Aurget v4 config file. Place this file at:
#
#  $XDG_CONFIG_HOME/aurgetrc
#
# Which is typically:
#
#  ~/.config/aurgetrc
#
###

# The directory within which to build.
build_directory="$PWD"

# Should aurget remove the extracted source directory after processing?
discard_sources=true

# When to edit PKGBUILDs. One of prompt, always, or never.
edit_pkgbuilds='prompt'

# If you choose to discard sources, you can separately choose to NOT
# discard sources for development packages.
keep_devels=true

# The makepkg executable
makepkg='makepkg'

# The default options to pass to makepkg. Other options may be added for
# you depending on the package (--asdeps) or sync_mode (--install).
makepkg_options='--syncdeps'

# When true, aurget will auto-answer all internal prompts as well as
# pass --noconfirm onto makepkg.
noconfirm=false

# When true, aurget will source PKGBUILDs and attempt to resolve
# dependencies.
resolve_dependencies=false

# The default way to search with -Ss. Can be one of search, info, quiet,
# or print.
search_mode='search'

# The default way to process packages for -S and -Su. Can be one of
# download, build, or install.
sync_mode='build'

# Where aurget will place temporary working files as needed. This
# directory is created and cleared when aurget starts.
temp_directory='/tmp/aurget'
