#!/bin/bash

_aurget() {
  local cur prev longopts ng_set aurget_exec aurget

  # save current nullglob setting and turn it on
  ng_set=$(shopt -p nullglob)
  shopt -s nullglob

  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  prev=${COMP_WORDS[COMP_CWORD-1]}

  # get full executable
  aurget_exec=$(type -P aurget)
  [[ -z "$aurget_exec" ]] && return 0

  # get short executable too
  aurget=$(basename "$aurget_exec")

  # valid long options
  longopts='--devel --deps --nodeps --edit --noedit \
            --discard --nodiscard --nocolor --noconfirm'

  # all valid options
  allopts='-S -Sd -Sb -Sy -Su -Sdu -Sbu -Syu -Ss -Ssq -Sp -Si \
           --devel --deps --nodeps --edit --noedit --discard \
           --nodiscard --nocolor --noconfirm --ignore --mopt \
           --popt --version --help'

  if [[ $(id -u) -eq 0 ]]; then
    aurget_exec+=' --asroot'
    longopts+=' --asroot'
  fi

  case "$prev" in
    # complete with all opts
    *$aurget) COMPREPLY=($(compgen -W "$allopts" -- $cur)) ;;

    # don't complete beyond these
    -h|-v|--@(help|version|ignore|@(m|p)opt)) return 0 ;;

    # complete with long opts
    -S*u*|--*) COMPREPLY=($(compgen -W "$longopts" -- $cur)) ;;

    # complete with package search
    -S*) COMPREPLY=($(compgen -W "$($aurget_exec -Ssq $cur)" -- $cur)) ;;
  esac

  # restore the previous nullglob setting
  $ng_set
}

complete -F _aurget aurget
